using System.Security.Cryptography;
namespace P90.GameAdapter;

public static class BuildGuard
{
    // Original binary fingerprints, not interop DLLs generated by a tool.
    public static string Verify(string root)
    {
        var expected = new Dictionary<string, string>
        {
            ["GameAssembly.dll"] = "BA69D16EDCE7B6FB2362823B8D7285B9905105C648289F0F25CBCCDB9973164A",
            ["UnityPlayer.dll"] = "31E826FDA8753714B682E71E8963EFCAA9C62C74E137ACE8D9719FAF50F9A3CE",
            ["SCP Project 90.exe"] = "5C9F655865DB8429F3BBC505A6BEC76243B82DAF979DE4346B61A9F010FD8EA5",
            ["SCP Project 90_Data/globalgamemanagers"] = "EEB90E77FF67B797D893F065197566355420299ECF1D55FE476A40E2F8724AE7",
            ["SCP Project 90_Data/il2cpp_data/Metadata/global-metadata.dat"] = "D534D60293659137FAA2E196444266909EBF472863A58E18F995038F831C4689",
            ["SCP Project 90_Data/ScriptingAssemblies.json"] = "49E290D7D0C71E5CC90DF2757A4DD3B5C2604920F4D1FC3B3D76DC098E1E6959"
        };
        foreach (var item in expected)
        {
            try
            {
                using var file = File.OpenRead(Path.Combine(root, item.Key));
                using var sha = SHA256.Create();
                if (Convert.ToHexString(sha.ComputeHash(file)) != item.Value) return "Unsupported game build: " + item.Key;
            }
            catch (Exception error) when (error is IOException or UnauthorizedAccessException) { return "Cannot verify game build: " + item.Key; }
        }
        return "";
    }
}
