<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.3.0</Version>
    <GameRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\'))</GameRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\P90.Core\P90.Core.csproj" />
    <ProjectReference Include="..\P90.GameAdapter\P90.GameAdapter.csproj" />
    <Reference Include="Assembly-CSharp" HintPath="$(GameRoot)BepInEx\interop\Assembly-CSharp.dll" Private="false" />
    <Reference Include="Mirror" HintPath="$(GameRoot)BepInEx\interop\Mirror.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(GameRoot)BepInEx\interop\Unity.TextMeshPro.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(GameRoot)BepInEx\interop\UnityEngine.UI.dll" Private="false" />
    <Reference Include="BepInEx.Core" HintPath="$(GameRoot)BepInEx\core\BepInEx.Core.dll" Private="false" />
    <Reference Include="BepInEx.Unity.IL2CPP" HintPath="$(GameRoot)BepInEx\core\BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="$(GameRoot)BepInEx\core\Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GameRoot)BepInEx\interop\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="Il2Cppmscorlib" HintPath="$(GameRoot)BepInEx\interop\Il2Cppmscorlib.dll" Private="false" />
  </ItemGroup>
</Project>
